### ISSUE TITLE
Introduce Google Auth

### ISSUE THREAD

**Issue by vigneshshettyin** [vigneshshettyin/Meetly#41]
### Description

Provide google auth as an alternative login system using firebase auth.

### Domain

Android (Kotlin)

### Code of Conduct

- [X] I follow [Code of Conduct](https://github.com/vigneshshettyin/Meetly/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by aayushpathak11** [comment]
@vigneshshettyin sir,
Can I take this up?

**Comment by vigneshshettyin** [comment]
Yes, @aayushpathak11 assigning this issue to you!

**Comment by aayushpathak11** [comment]
@vigneshshettyin sir 
A small doubt - 
Since this issue requires enabling google sign in from firebase authentication and then adding web_client_id in the manner shown below - 
![image](https://user-images.githubusercontent.com/77546902/162583523-7ed7f043-09f3-4d0a-a5b7-2874ade13db9.png)
I did this in my Firebase project but you would have to enable it manually in yours, right?

**Comment by vigneshshettyin** [comment]
Yes, I will enable it in the firebase console. Please make sure necessary entry is made in the fire store when a new user registers using google auth. Google auth button use the default one available and also handle the light/dark mode as well. 

@aayushpathak11
